### ISSUE TITLE
Update fog-core Version in Gemspec

### ISSUE THREAD

**Issue by maham-nazir-confiz** [fog/fog-json#11]
I recently upgraded to the latest version of `fog-core` which is `v2.0.0` but this is causing my `fog-json` gem to break down as it has a pessimistic dependency on `fog-core ~> 1.0`.
Is it possible to bump the `fog-core` version in `fog-json` and release a new version of `fog-json`?

**Comment by plribeiro3000** [comment]
cc/ @geemus

**Comment by geemus** [comment]
Thanks for the heads up, released as fog-json v1.1.0
