### ISSUE TITLE
Remove Duplicated LICENSE

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-json#7]
cc/ @geemus @tokengeek 

I was going to create a pull request but i'm afraid i would miss who contributed to the json piece of code.

What i'm doing in the providers is to use: `git shortlog -sne tests/provider` to get the contributors.

**Comment by geemus** [comment]
for contributors I use osrcry usually to generate it (ditto with license) not sure if that helps.

**Comment by plribeiro3000** [comment]
Yeah. I'm not using your project (osrcry) to do this jobs because i wanted to list the CONTRIBUTORS from the main `Fog` gem as well.

As i could see [here](https://github.com/fog/fog-json/blob/master/CONTRIBUTORS.md) it is listing just you but it seems @tokengeek did some commits here as well. =)

**Comment by geemus** [comment]
I probably just haven't re-run it. Stuff from fog as well is definitely a harder problem.

**Comment by geemus** [comment]
Thanks!
